{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPD3sm6JRu22LkH+jsaMYGl"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/adityagnayak/Finance-Projects/blob/main/retirement_webpage.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 383
        },
        "id": "R3-vYWL7vKAJ",
        "outputId": "e96ad3d7-7d2e-409b-8ac0-5d4b71571acf"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'streamlit'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipython-input-2728599720.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mstreamlit\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mst\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;31m# --- PAGE CONFIGURATION ---\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m st.set_page_config(\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'streamlit'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "import streamlit as st\n",
        "import pandas as pd\n",
        "\n",
        "# --- PAGE CONFIGURATION ---\n",
        "st.set_page_config(\n",
        "    page_title=\"Retirement Engine v8.0\",\n",
        "    page_icon=\"📈\",\n",
        "    layout=\"wide\"\n",
        ")\n",
        "\n",
        "# --- CLASS DEFINITION (Adapted for Web) ---\n",
        "class RetirementPlanner:\n",
        "    def __init__(self, inputs):\n",
        "        self.inputs = inputs\n",
        "        self.lump_sum = inputs['lump_sum']\n",
        "        self.horizon_months = int(inputs['horizon_years'] * 12)\n",
        "\n",
        "    def calculate_viability(self, crash_rate=0.0, crash_years=0):\n",
        "        balance = self.lump_sum\n",
        "        current_div = self.inputs['current_dividends']\n",
        "        current_expense = self.inputs['target_payout']\n",
        "\n",
        "        data = []\n",
        "        is_solvent = True\n",
        "        insolvency_msg = \"Solvent\"\n",
        "\n",
        "        for m in range(1, self.horizon_months + 1):\n",
        "            year = (m - 1) // 12 + 1\n",
        "\n",
        "            # Crash Logic\n",
        "            if year <= crash_years:\n",
        "                monthly_rate = crash_rate / 12\n",
        "            else:\n",
        "                monthly_rate = self.inputs['expected_return'] / 12\n",
        "\n",
        "            # Inflation Adjustments\n",
        "            if m > 1 and (m - 1) % 12 == 0:\n",
        "                current_div *= (1 + self.inputs['gdp_growth'])\n",
        "                current_expense *= (1 + self.inputs['inflation_rate'])\n",
        "\n",
        "            # Core Logic\n",
        "            balance += (balance * monthly_rate) # Interest\n",
        "            total_income = self.inputs['other_income'] + current_div\n",
        "            net_shortfall = max(0, current_expense - total_income)\n",
        "            gross_withdrawal = net_shortfall / (1 - self.inputs['tax_rate']) # Tax Drag\n",
        "            balance -= gross_withdrawal\n",
        "\n",
        "            if balance <= 0 and is_solvent:\n",
        "                is_solvent = False\n",
        "                insolvency_msg = f\"DEPLETED (Year {year})\"\n",
        "                balance = 0\n",
        "\n",
        "            if m % 12 == 0 or m == self.horizon_months:\n",
        "                data.append({\n",
        "                    \"Year\": year,\n",
        "                    \"Expenses (Net)\": current_expense,\n",
        "                    \"Withdrawal (Gross)\": gross_withdrawal,\n",
        "                    \"Balance\": balance\n",
        "                })\n",
        "\n",
        "        return pd.DataFrame(data), is_solvent, insolvency_msg\n",
        "\n",
        "    def solve_required_capital(self, crash_rate=0, crash_years=0):\n",
        "        original_balance = self.lump_sum\n",
        "        low = self.lump_sum\n",
        "        high = self.lump_sum * 10\n",
        "\n",
        "        for _ in range(30):\n",
        "            mid = (low + high) / 2\n",
        "            self.lump_sum = mid\n",
        "            _, solvent, _ = self.calculate_viability(crash_rate, crash_years)\n",
        "            if solvent: high = mid\n",
        "            else: low = mid\n",
        "\n",
        "        required = high\n",
        "        self.lump_sum = original_balance\n",
        "        return required\n",
        "\n",
        "    def calculate_swr_health(self):\n",
        "        initial_gap = self.inputs['target_payout'] - (self.inputs['other_income'] + self.inputs['current_dividends'])\n",
        "        if initial_gap <= 0: return 0.0, \"SECURE\"\n",
        "\n",
        "        gross_annual = (initial_gap * 12) / (1 - self.inputs['tax_rate'])\n",
        "        if self.lump_sum <= 0: return 0.0, \"CRITICAL\"\n",
        "\n",
        "        rate = gross_annual / self.lump_sum\n",
        "        if rate <= 0.035: return rate, \"EXCELLENT (< 3.5%)\"\n",
        "        elif rate <= 0.045: return rate, \"GOOD (Industry Std)\"\n",
        "        elif rate <= 0.06: return rate, \"RISKY (High Risk)\"\n",
        "        else: return rate, \"DANGER (> 6.0%)\"\n",
        "\n",
        "# --- SIDEBAR: INPUTS ---\n",
        "st.sidebar.header(\"📝 Financial Inputs\")\n",
        "\n",
        "# Group 1: Assets\n",
        "with st.sidebar.expander(\"Assets & Income\", expanded=True):\n",
        "    lump_sum = st.number_input(\"Total Capital ($)\", value=500000, step=10000)\n",
        "    other_inc = st.number_input(\"Fixed Income ($/mo)\", value=1500, step=100)\n",
        "    curr_div = st.number_input(\"Dividend Income ($/mo)\", value=500, step=50)\n",
        "\n",
        "# Group 2: Goals\n",
        "with st.sidebar.expander(\"Expenses & Taxes\", expanded=True):\n",
        "    target_payout = st.number_input(\"Target Spend ($/mo)\", value=4000, step=100)\n",
        "    tax_rate = st.slider(\"Tax Rate (%)\", 0, 50, 15) / 100\n",
        "    horizon = st.slider(\"Horizon (Years)\", 10, 50, 25)\n",
        "\n",
        "# Group 3: Market\n",
        "with st.sidebar.expander(\"Market Assumptions\", expanded=False):\n",
        "    inflation = st.slider(\"Inflation Rate (%)\", 0.0, 10.0, 2.5) / 100\n",
        "    gdp = st.slider(\"Div Growth Rate (%)\", 0.0, 10.0, 3.0) / 100\n",
        "\n",
        "# --- MAIN PAGE: PORTFOLIO ARCHITECT ---\n",
        "st.title(\"Retirement Engine v8.0\")\n",
        "st.markdown(\"### 🏛️ Portfolio Architect\")\n",
        "\n",
        "col1, col2 = st.columns(2)\n",
        "\n",
        "with col1:\n",
        "    strategy = st.selectbox(\"Select Strategy\", [\"Aggressive Growth\", \"Conservative Income\", \"Custom Allocation\"])\n",
        "\n",
        "est_return = 0.07\n",
        "\n",
        "if strategy == \"Aggressive Growth\":\n",
        "    alloc = {'Equity': 60, 'Metals': 20, 'Debt': 10, 'Cash': 10}\n",
        "    est_return = 0.08\n",
        "elif strategy == \"Conservative Income\":\n",
        "    alloc = {'Equity': 20, 'Metals': 10, 'Debt': 40, 'Cash': 30}\n",
        "    est_return = 0.05\n",
        "else:\n",
        "    st.info(\"Define Custom Mix (Must sum to 100)\")\n",
        "    c1, c2, c3, c4 = st.columns(4)\n",
        "    e = c1.number_input(\"Equity %\", 0, 100, 50)\n",
        "    m = c2.number_input(\"Metals %\", 0, 100, 10)\n",
        "    d = c3.number_input(\"Debt %\", 0, 100, 30)\n",
        "    c = c4.number_input(\"Cash %\", 0, 100, 10)\n",
        "    alloc = {'Equity': e, 'Metals': m, 'Debt': d, 'Cash': c}\n",
        "    # Simple weighted calc\n",
        "    est_return = (e*0.09 + m*0.04 + d*0.04 + c*0.02) / 100\n",
        "\n",
        "with col2:\n",
        "    st.write(f\"**Target Allocation:** {alloc}\")\n",
        "    final_return = st.number_input(f\"Expected Return (Hist: {est_return*100:.1f}%)\", value=est_return)\n",
        "\n",
        "# --- RUN SIMULATION ---\n",
        "inputs = {\n",
        "    'lump_sum': lump_sum, 'other_income': other_inc, 'current_dividends': curr_div,\n",
        "    'target_payout': target_payout, 'tax_rate': tax_rate, 'horizon_years': horizon,\n",
        "    'inflation_rate': inflation, 'gdp_growth': gdp, 'expected_return': final_return\n",
        "}\n",
        "\n",
        "planner = RetirementPlanner(inputs)\n",
        "df_base, solv_base, msg_base = planner.calculate_viability()\n",
        "swr, swr_status = planner.calculate_swr_health()\n",
        "\n",
        "# --- DASHBOARD RESULTS ---\n",
        "st.markdown(\"---\")\n",
        "m1, m2, m3 = st.columns(3)\n",
        "m1.metric(\"Initial Withdrawal Rate\", f\"{swr*100:.2f}%\", swr_status)\n",
        "m2.metric(\"Base Scenario Result\", msg_base, delta_color=\"normal\" if solv_base else \"inverse\")\n",
        "\n",
        "if not solv_base:\n",
        "    req = planner.solve_required_capital()\n",
        "    m3.metric(\"Required Capital\", f\"${req:,.0f}\", f\"+${req-lump_sum:,.0f} needed\")\n",
        "else:\n",
        "    m3.metric(\"Ending Balance\", f\"${df_base.iloc[-1]['Balance']:,.0f}\")\n",
        "\n",
        "# Charts\n",
        "st.subheader(\"📊 Capital Trajectory (Base Case)\")\n",
        "st.line_chart(df_base, x=\"Year\", y=\"Balance\")\n",
        "\n",
        "# --- STRESS TEST SECTION ---\n",
        "st.markdown(\"---\")\n",
        "st.subheader(\"🌪️ Dynamic Stress Test\")\n",
        "\n",
        "with st.expander(\"Configure Crash Scenario\", expanded=True):\n",
        "    sc1, sc2 = st.columns(2)\n",
        "    crash_pct = sc1.slider(\"Crash Magnitude (%)\", -50, 0, -20) / 100\n",
        "    crash_yrs = sc2.slider(\"Crash Duration (Years)\", 0, 10, 2)\n",
        "\n",
        "    if st.button(\"Run Stress Test\"):\n",
        "        df_stress, solv_stress, msg_stress = planner.calculate_viability(crash_pct, crash_yrs)\n",
        "\n",
        "        st.write(f\"**Outcome:** {msg_stress}\")\n",
        "\n",
        "        # Comparison Chart\n",
        "        combined_df = pd.DataFrame({\n",
        "            \"Year\": df_base[\"Year\"],\n",
        "            \"Base Case\": df_base[\"Balance\"],\n",
        "            \"Stress Test\": df_stress[\"Balance\"]\n",
        "        })\n",
        "        st.line_chart(combined_df, x=\"Year\", y=[\"Base Case\", \"Stress Test\"])\n",
        "\n",
        "        if not solv_stress:\n",
        "            req_stress = planner.solve_required_capital(crash_pct, crash_yrs)\n",
        "            st.error(f\"🚨 To survive this crash, you need a Total Capital of **${req_stress:,.0f}**\")"
      ]
    }
  ]
}
